### ISSUE TITLE
Turn 'constraints' in tach.yml into a list of dictionaries

### ISSUE THREAD

**Issue by emdoyle** [Never-Over/tach#52]
Ref #51 

This is a dependency for allowing centralized config in pyproject.toml (#49)

We should change the type of 'constraints' in tach.yml from a dictionary with tags each as keys into a list of dictionaries, with each dictionary specifying its 'name' as a string. This avoids any issues with special characters like dots and colons when using TOML.

Current:
```
constraints:
  scope:filesystem:
    depends_on:
    - scope:utils
  scope:parsing:
    depends_on:
    - scope:core
    - scope:filesystem
  scope:root:
    depends_on:
    - scope:utils
    - scope:core
    - scope:filesystem
    - scope:parsing
exclude:
- tests/
- docs/
exclude_hidden_paths: true
```

Proposed:
```
constraints:
  - name: scope:filesystem
    depends_on:
    - scope:utils
  - name: scope:parsing
    depends_on:
    - scope:core
    - scope:filesystem
  - name: scope:root
    depends_on:
    - scope:utils
    - scope:core
    - scope:filesystem
    - scope:parsing
exclude:
- tests/
- docs/
exclude_hidden_paths: true
```
